previewsEnabled: true
previewsExpireAfterDays: 1

services:
  - type: web
    name: nest-test
    region: oregon
    plan: free
    branch: master
    # domains:
    #   - api.coolapp.dev
    startCommand: yarn run start:prod


