previewsEnabled: true
previewsExpireAfterDays: 1

services:
  - type: web
    name: nest-test
    env: node
    region: oregon
    plan: free
    branch: master
    # domains:
    #   - api.coolapp.dev
    startCommand: yarn run start:prod
    envVars:
      - key: PORT
        value: 4000

